### PR TITLE
modify port to 3000

### PR DESCRIPTION
**Pull request by Thinkingsmonkey**
老師好，我是 邱元弘，麻煩老師了!

### CODE REVIEW

**Comment by Thinkingsmonkey** [comment]
老師有看到嗎？ 第一次邀請人不太清楚流程@@

**Comment by cwpeng** [comment]
Add protection rule to your `main` branch.

**Comment by Thinkingsmonkey** [comment]
有把保護規則加進去了

**Comment by cwpeng** [comment]
Something wrong, check again. You will see "require at least 1 review to merge" in this page if it set up properly.

**Comment by Thinkingsmonkey** [comment]
有再次修改了

**Review by cwpeng — APPROVED** [review]
ok.

**Pull request merged**
