### PR TITLE
add Part 1-2 three APIs

### PR DESCRIPTION
**Pull request by Thinkingsmonkey**
老師好，目前已經完成 1-2 的三個 API 準備 merge 到 main branch 上，讓 EC2 clone，麻煩老師校閱

### CODE REVIEW

**Comment by Thinkingsmonkey** [comment]
老師我已經將 server 部署到 aws 上了，再請老師校閱一下，謝謝老師
http://54.65.247.64:3000/api/mrts

**Review by cwpeng — COMMENTED** [review]
1. We should assume data will grow or change in the future, so `if page > 4 or page < 0:` is a bad way to judge if page is valid.
2. We never get data all at once like this `Attraction.query.all()`.

Re-request review and leave comment here after you fixed them.

**Comment by Thinkingsmonkey** [comment]
老師我將搜尋條件修改為 page 為主了，再請老師幫忙校閱

**Comment by cwpeng** [comment]
Looks OK. But who are you?

**Comment by Thinkingsmonkey** [comment]
老師好，我是 邱元弘

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
