### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Thinkingsmonkey**
老師好我是 邱元弘，已經完成本周任務
連結是 https://flask-react.to-do-app.com/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. I signed up a new account but cannot sign in by that. Always response `email not existed`.
2. Show proper error message if email is repeated in signing up procedure.

**Comment by Thinkingsmonkey** [comment]
老師好，剛剛測試了一下，發現在沒有更改代碼情況下，註冊與登入是正常的，還是請老師再試試看？
我有上傳測試影片在 discord 的私聊上，在請老師看一下

**Comment by cwpeng** [comment]
Checked again. The same issues.

**Comment by Thinkingsmonkey** [comment]
老師好，我將 signup 的 data 做了修正，現在會正確使用 payload 的 email、password 了
另外當重複的 email 出現我使用的是 https://github.com/Thinkingsmonkey/taipei-day-trip/blob/618c41c749bf5bf7d49dd68fac43e4b272c4be2a/server/routes/member/member_controller.py#L20
回傳 【"Email has been used"】並在前端的 button 下顯示相同的 error message，這樣的過程是符合的嗎？

**Review by cwpeng — APPROVED** [review]
OK. Done.

For fullfilling API spec, the point is what response we actually get after calling an API, not how you implement it.

And, you use flask_jwt_extended module to implement it, it hides many details. make sure you know how JWT works even if you have completed this task.

**Pull request merged**
